version: '3.3'

services:
  proxy:
    image: sourcelair/ceryx-proxy:latest
    ports:
      - ${CERYX_EXTERNAL_PORT:-80}:80
      - ${CERYX_EXTERNAL_SSL_PORT:-443}:443
    depends_on:
      - redis
    environment:
      CERYX_REDIS_HOST: ${CERYX_REDIS_HOST:-redis}
      CERYX_REDIS_PORT: ${CERYX_REDIS_PORT:-6379}
      
  api:
    image: sourcelair/ceryx-api:latest
    depends_on:
      - redis
      - proxy
    environment:
      CERYX_REDIS_HOST: ${CERYX_REDIS_HOST:-redis}
      CERYX_REDIS_PORT: ${CERYX_REDIS_PORT:-6379}
      CERYX_API_HOST: ${CERYX_API_HOST:-0.0.0.0}
      CERYX_API_PORT: ${CERYX_API_PORT:-5555}
      CERYX_API_HOSTNAME: ${CERYX_API_HOSTNAME:-localhost}
      CERYX_DEBUG: ${CERYX_DEBUG:-false}
      
  redis:
    image: redis:3.2.3-alpine
